"""add student profile

Revision ID: 47a17897c3f0
Revises: e43415a0feda
Create Date: 2024-11-09 10:37:39.753582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a17897c3f0'
down_revision = 'e43415a0feda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('Author',
               existing_type=sa.VARCHAR(length=100),
               nullable=100)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StudentProfile', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('StudentProfile')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('Author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
