"""updates book and student

Revision ID: 71b6f99c6621
Revises: 2a4bc231861d
Create Date: 2024-11-11 09:01:30.877520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b6f99c6621'
down_revision = '2a4bc231861d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BookPoster', sa.String(length=255), nullable=False))
        batch_op.alter_column('Author',
               existing_type=sa.VARCHAR(length=100),
               nullable=100)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StudentProfile', sa.String(length=255), nullable=False))
        batch_op.alter_column('EmailAddress',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('EmailAddress',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('StudentProfile')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('Author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('BookPoster')

    # ### end Alembic commands ###
